site_name: AAD

theme:
  name: "material"
  palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - toc.follow
    - content.tooltips

plugins:
- search
- markdown-exec
- autorefs
- mkdocstrings:
    handlers: 
      python:
        import:
          - https://docs.python.org/3/objects.inv
          - https://networkx.org/documentation/stable/objects.inv
          - https://numpy.org/doc/stable/objects.inv
          - https://docs.scipy.org/doc/scipy/objects.inv
        options:
          docstring_style: numpy
          docstring_section_style: list
          show_bases: false
          show_source: false
          # Headings
          show_root_heading: true
          show_root_full_path: false
          heading_level: 3
          show_symbol_type_toc: true
          show_symbol_type_heading: true
          # Members
          group_by_category: true
          show_labels: false
          # Signatures
          annotations_path: brief
          separate_signature: false
          show_signature_annotations: true
          modernize_annotations: true
          line_length: 80
          signature_crossrefs: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      auto_append:
        - docs-includes/abbreviations.md
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - API:
    - API: api/index.md
    - Data: api/datasets.md